Repository theforeman/foreman_bootdisk, pull requests merged in 2018-10, with the labels that each got.

#66 Refs #21833 - fixed initialization order for bootsnap
  lib/foreman_bootdisk/engine.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#65 fixes #24147 - use new template renderer
  app/controllers/foreman_bootdisk/disks_controller.rb
  app/lib/foreman_bootdisk/scope/bootdisk.rb
  app/models/concerns/foreman_bootdisk/host_ext.rb
  app/services/foreman_bootdisk/renderer.rb
  app/services/foreman_bootdisk/renderer_methods.rb
  lib/foreman_bootdisk/engine.rb
  test/models/host/managed_test.rb
  test/unit/foreman_bootdisk/renderer_test.rb
  test/unit/foreman_bootdisk/scope/bootdisk_test.rb
Labels: Needs testing, Not yet reviewed

#68 fixes #25121 - remove explicit asset precompile
  lib/foreman_bootdisk/engine.rb
Labels: Needs testing

#70 fixes #25206 - add rubocop linting
  .rubocop.yml
  Gemfile
  app/controllers/foreman_bootdisk/api/v2/disks_controller.rb
  app/controllers/foreman_bootdisk/api/v2/subnet_disks_controller.rb
  app/controllers/foreman_bootdisk/disks_controller.rb
  app/helpers/concerns/foreman_bootdisk/hosts_helper_ext.rb
  app/lib/foreman_bootdisk/scope/bootdisk.rb
  app/lib/foreman_bootdisk/scope/full_host_bootdisk.rb
  app/models/concerns/foreman_bootdisk/compute_resources/vmware.rb
  app/models/concerns/foreman_bootdisk/host_ext.rb
  app/models/concerns/foreman_bootdisk/orchestration/compute.rb
  app/models/setting/bootdisk.rb
  app/services/foreman_bootdisk/iso_generator.rb
  app/services/foreman_bootdisk/renderer.rb
  config/routes.rb
  config/routes/mount_engine.rb
  db/migrate/20130914211030_create_host_bootdisk_template.rb
  db/migrate/20130915104500_edit_host_bootdisk_template_multinic.rb
  db/migrate/20130915133321_create_kickstart_bootdisk_template.rb
  db/migrate/20130915201457_create_generic_host_bootdisk_template.rb
  db/migrate/20131021095100_edit_host_bootdisk_template_dns_secondary.rb
  db/migrate/20140522185700_change_templatekind_to_bootdisk.rb
  db/migrate/20171009225200_remove_duplicate_bootdisk_templates.rb
  db/seeds.d/50-bootdisk_templates.rb
  foreman_bootdisk.gemspec
  lib/foreman_bootdisk.rb
  lib/foreman_bootdisk/engine.rb
  lib/foreman_bootdisk/version.rb
  lib/tasks/bootdisk.rake
  locale/gemspec.rb
  test/functional/foreman_bootdisk/api/v2/disks_controller_test.rb
  test/functional/foreman_bootdisk/api/v2/subnet_disks_controller_test.rb
  test/functional/foreman_bootdisk/disks_controller_test.rb
  test/models/host/managed_test.rb
  test/test_plugin_helper.rb
  test/unit/access_permissions_test.rb
  test/unit/concerns/compute_resources/vmware_test.rb
  test/unit/concerns/host_test.rb
  test/unit/concerns/orchestration/compute_test.rb
  test/unit/foreman_bootdisk/renderer_test.rb
  test/unit/foreman_bootdisk/scope/bootdisk_test.rb
  test/unit/foreman_bootdisk/scope/full_host_bootdisk_test.rb
  test/unit/iso_generator_test.rb
Labels: Needs testing
